version: "3"
services:
  airsonic:
    image: airsonic/airsonic:latest
    ports:
      - "4040:4040"
    restart: unless-stopped
    volumes:
      - "/home/jon/Dropbox:/airsonic/music:ro"
      - "/home/jon/airsonic:/airsonic/data:rw"
  dropbox:
    image: otherguy/dropbox:latest
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      DROPBOX_UID: 1000
      DROPBOX_GID: 1000
    volumes:
      - "/home/jon/Dropbox:/opt/dropbox/Dropbox:rw"
      - "/home/jon/DropboxConfig:/opt/dropbox/.dropbox:rw"
